### ISSUE TITLE
Streaming stdout/stderr

### ISSUE THREAD

**Issue by benmerckx** [haxetink/tink_io#8] opened 2016-06-13 14:37 UTC
While reworking the tink_http tests I'm trying to use tink_io to stream stdout/stderr of the server process while the tests are running to ease debugging. I need to do this in an async way so figured I only need to add tink_runloop for this to work. Basically I'm seeing things like the example below fail. This works when compiled with only `-lib tink_io` but fails when I add `-lib tink_runloop` or `-lib tink_runloop -D concurrent`. The trace of the exit code always works but I don't get anything piped to the terminal. Is there something I'm missing?

``` haxe
import sys.io.Process;
import tink.io.Sink;
import tink.io.Source;

class Main {
    static function main() {
        var process = new Process('ls', []);
        Source.ofInput('process stdout', process.stdout).pipeTo(Sink.stdout);
        Source.ofInput('process stderr', process.stderr).pipeTo(Sink.stdout);
        trace('Exit: '+process.exitCode());
    }
}
```

**Comment by back2dos** [comment] 2016-06-13 20:29
Uhm, nope, that's my fault. The problem is that the runloop is not retained
by the streams, so it exits before all the piping is done. Will look into
it.

**Comment by back2dos** [comment] 2016-06-14 09:13
For now I think you could do `#if tink_runloop tink.RunLoop.current.retain() #end` though. If you're not exiting manually, you will need to `cancel` the `Task` returned, so the loop can exit.

**Comment by benmerckx** [comment] 2016-06-14 09:52
Doesn't seem to work for me. Also, if I don't cancel the task or exit manually, the execution still stops after the trace. I'm testing on neko.

Messing a bit more with the example and checking out tink_runloop I'm thinking the extraParams (`tink.runloop.Boot.boot()`) are simply not applied. Well, it does run probably but I think this is an issue with syntaxhub. When I dump the code the main is not wrapped in `tink.RunLoop.create`. If I manually wrap the main in it everything seems to work!

**Comment by benmerckx** [comment] 2016-06-14 10:35
I was using `-x Main` to compile the example. And in the tests the main is wrapped in `#!if macro` calls. Which are probably two edge cases not handled by sytaxhub.

**Comment by back2dos** [comment] 2016-06-14 10:52
So if you use `-x` then `-D macro` is set?

**Comment by benmerckx** [comment] 2016-06-14 10:55
No they're unrelated. I used `-x` for the basic example above, [which isn't checked](https://github.com/haxetink/tink_syntaxhub/blob/master/src/tink/SyntaxHub.hx#L22).

The problems I had when rewriting the tests were the same, but I think those were causing by having a main method wrapped in `#if !macro` which might cause syntaxhub to 'not see it'. While I'm unsure that is the exact cause, I do not see the `tink.RunLoop.create` there either and adding it manually works.

**Comment by back2dos** [comment] 2016-07-14 14:55
Ok, the underlying problem in tink_syntaxhub should be fixed now.

**Closed as completed by back2dos** 2016-07-14 14:55 UTC
